# Generated by Django 6.0 on 2025-12-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
    ]
