# Generated by Django 6.0 on 2025-12-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
